# Site settings
title: Billy Charlton
email: charlton@vsp.tu-berlin.de
description: > # this means to ignore newlines until "baseurl:"
  Data Scientist an der TU-Berlin. Ich entwickle interaktive Datenvisualisierungs- und Analysetools für die Modellierung großer Systeme.
baseurl: "/de" # the subpath of your site, e.g. /blog
url: "https://billyc.github.io" # the base hostname & protocol for your site
production_url: "https://billyc.github.io"
github_username: billyc
permalink: /blog/:year/:month/:title.html

twitter:
  username: billyinberlin

sass:
  style: compressed

collections:
  publications:
    output: false

jekyll-mentions:
  base_url: https://twitter.com

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-mentions
