# - position: Organizer
#   at: DSIA at VIS 2018
#   url: http://www.interactive-analysis.org/
#
# - position: Program Committee
#   at: HILDA at SIGMOD 2018
#   url: http://hilda.io/2018/
- year: 2016-2020
  title: "Zephyr Foundation for Advancing Travel Forecasting"
  text: "Mitbegründer und Vorstandsvorsitzender. Gründung einer neuen gemeinnützigen Stiftung zur Förderung der technischen Fähigkeiten auf dem Gebiet der Verkehrsprognose."

- year: 2007-2016
  title: Transportation Research Board Committee on Transportation Demand Forecasting (ADB40)
  text: "Ausschussmitglied, zuständig für die Überprüfung wissenschaftlicher Arbeiten und die technische Leitung."
